# Generated by Django 4.2.2 on 2023-07-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_colorvarient_sizevarient_products_color_varient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color_varient',
            field=models.ManyToManyField(blank=True, to='products.colorvarient'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_varient',
            field=models.ManyToManyField(blank=True, to='products.sizevarient'),
        ),
    ]
