# Generated by Django 4.2.2 on 2023-08-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_color_varient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color_varient',
            field=models.ManyToManyField(blank=True, related_name='color', to='products.colorvarient'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_varient',
            field=models.ManyToManyField(blank=True, related_name='size', to='products.sizevarient'),
        ),
    ]
